---
- hosts: all

  tasks:
    - include_role:
        name: 2PRecuperatorio
    
    - include_role:
        name: Instala-tools_RiveraMendes    
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

