---
  - name: Instalar programas en hosts
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "htop"
      - "net-tools"
      - "tmux"
      - "tree"
      - "speedtest-cli"
